#if !canImport(ObjectiveC)
import XCTest

extension CustomEncoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CustomEncoderTests = [
        ("testBase64DataDecoding", testBase64DataDecoding),
        ("testHex0xDataEncoding", testHex0xDataEncoding),
        ("testHexDataDecoding", testHexDataDecoding),
        ("testHexDataEncoding", testHexDataEncoding),
    ]
}

extension SerializableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SerializableTests = [
        ("testDecoding", testDecoding),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CustomEncoderTests.__allTests__CustomEncoderTests),
        testCase(SerializableTests.__allTests__SerializableTests),
    ]
}
#endif
